### ISSUE TITLE
How to evaluate?

### ISSUE THREAD

**Issue by tongxuluo** [microsoft/Samba#15]
We tried to pretrain a 421M Samba, but after pretraining, we find that you did not open source the evaluation script.

**Comment by richardburleigh** [comment]
I've hacked together Huggingface Transformers support for a model I'm training at the moment, which allows Samba to work with [EleutherAI/lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness)

It's too messy to share at the moment, but if you're comfortable posting your model I can run whichever evals you'd like. Otherwise hopefully the Samba team will get the approval they deserve and can release the official Transformers support for this amazing architecture.

**Comment by tongxuluo** [comment]
> I've hacked together Huggingface Transformers support for a model I'm training at the moment, which allows Samba to work with [EleutherAI/lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness)
> 
> It's too messy to share at the moment, but if you're comfortable posting your model I can run whichever evals you'd like. Otherwise hopefully the Samba team will get the approval they deserve and can release the official Transformers support for this amazing architecture.

Wow, thank you very much! We have already uploaded the checkpoints on Huggingface: https://huggingface.co/wydu/Samba . We would greatly appreciate it if you could help us evaluate the checkpoints `Samba-iter-200000-ckpt.pth` and `Samba2-iter-188000-ckpt.pth` on the following tasks: `lambada_openai`, `wikitext`, `piqa`, `sciq`, `winogrande`, `arc_challenge`, `arc_easy`, and `logiqa`.
